# Generated by Django 4.0.2 on 2022-06-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=30)),
                ('book_desc', models.CharField(max_length=150)),
                ('book_price', models.FloatField()),
                ('book_Image', models.ImageField(upload_to='storefront/images')),
            ],
        ),
    ]
